### ISSUE TITLE
unable to open logfile with no clusters?

### ISSUE THREAD

**Issue by ingenthr** [spjmurray/logify#4]
I am not quite sure why, but I can create a logfile from my 2.0.2 based deployment (which failed to deploy a cluster) and I cannot use this to look at the logs either by pointing it to the .tar.gz or to it untarred.  Wants some metadata in either case.

```
% logify cbopinfo-20210412T214056-0700.tar.gz   
Traceback (most recent call last):
  File "/Users/ingenthr/src/logify/bin/logify", line 179, in <module>
    main()
  File "/Users/ingenthr/src/logify/bin/logify", line 150, in main
    logs, metadata = init(args, tempdir.name)
  File "/Users/ingenthr/src/logify/bin/logify", line 63, in init
    with open(args.logfile + '/metadata.json') as filedesc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/42/jb48df1n373_wzyfwrrj66140000gp/T/tmptxmiydy5/cbopinfo-20210412T214056-0700/metadata.json'
```

Is it because I have no active clusters?  I do have an operator deployment.  

```
% kubectl get po
NAME                                            READY   STATUS    RESTARTS   AGE
couchbase-operator-59ffb7f56-vvknd              1/1     Running   0          49m
couchbase-operator-admission-6d56b68b76-8zl9z   1/1     Running   0          49m
```

**Comment by spjmurray** [comment]
Archive metadata only exists in logs generated by cbopinfo 2.2+
